CREATE TABLE product (
    -- La columna 'id' como clave primaria autoincrementable.
    -- La clase Java usa 'int', pero en PostgreSQL se recomienda SERIAL o INT GENERATED BY DEFAULT AS IDENTITY
    -- para claves primarias enteras autoincrementables.
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- El atributo 'name' se mapea a un VARCHAR para cadenas de texto.
    -- Se asume un tamaño razonable y que no puede ser nulo.
    name VARCHAR(255) NOT NULL,

    -- El atributo 'description' también es una cadena de texto,
    -- usando TEXT para descripciones potencialmente más largas.
    description TEXT,

    -- El atributo 'price' es un float, que se mapea a NUMERIC o REAL/FLOAT en SQL.
    -- NUMERIC(precision, scale) es mejor para datos monetarios para evitar errores de coma flotante.
    price NUMERIC(10, 2) NOT NULL,

    -- El atributo 'stock' es un int, que se mapea a INTEGER en SQL.
    -- Se asume que no puede ser nulo y debe ser mayor o igual a cero.
    stock INTEGER NOT NULL CHECK (stock >= 0)
);

-- Procedimiento almacenado para actualizar un producto
CREATE OR REPLACE PROCEDURE update_product(
    p_id INT,
    p_name VARCHAR(255),
    p_description TEXT,
    p_price NUMERIC(10, 2),
    p_stock INT
)
LANGUAGE plpgsql
AS $$
BEGIN
	-- Verificar si el producto existe
    IF NOT EXISTS (SELECT 1 FROM product WHERE id = p_id) THEN
        RAISE EXCEPTION 'Producto con ID % no encontrado', p_id;
    END IF;

	-- Validación: El precio debe ser mayor a 0
    IF p_price <= 0 THEN
        RAISE EXCEPTION 'El precio debe ser mayor a 0';
    END IF;

    -- Actualizar el producto
    UPDATE product
    SET name = p_name,
        description = p_description,
        price = p_price,
        stock = p_stock
    WHERE id = p_id;
END;
$$;

CREATE OR REPLACE FUNCTION actualizar_stock(
    p_producto_id INTEGER,
    p_cantidad INTEGER
) RETURNS VOID AS $$
DECLARE
    current_stock INTEGER;
BEGIN
    -- Obtener stock actual
    SELECT stock INTO current_stock
    FROM product
    WHERE id = p_producto_id;

    -- Validar que el producto existe
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Producto con ID % no encontrado', p_producto_id;
    END IF;

    -- Validar que hay suficiente stock
    IF current_stock < p_cantidad THEN
        RAISE EXCEPTION 'Stock insuficiente. Stock actual: %, solicitado: %', current_stock, p_cantidad;
    END IF;

    -- Actualizar stock
    UPDATE product
    SET stock = stock - p_cantidad
    WHERE id = p_producto_id;
END;
$$ LANGUAGE plpgsql;


-- Función para obtener productos con bajo stock
CREATE OR REPLACE FUNCTION productos_bajo_stock(
    p_minimo INTEGER
) RETURNS TABLE(
    id INTEGER,
    name VARCHAR,
    stock INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT p.id, p.name, p.stock
    FROM product p
    WHERE p.stock < p_minimo;
END;
$$ LANGUAGE plpgsql;